/**
 * Banner ads configuration. Shared by client + server, so this file has NO
 * server-only imports. Mirrors the honest-state + approval rules of the DB.
 */

/** Feature flags for the banner ads system (billing is provider-gated). */
export const bannerFeatures = {
  enabled: true,
  cityTargeting: true,
  gujaratWide: true,
  approvalRequired: true,      // every ad goes through admin review
  paymentRequired: false,      // Razorpay for ads not wired → no fake payment
  desktopImageRequired: true,
  mobileImageRequired: false,
  analytics: false,            // no fake impression/click numbers
} as const;

/** Public roles allowed to create banner ads (builders promote their projects). */
export const BANNER_ELIGIBLE_ROLES = ["builder"] as const;
export function isBannerEligibleRole(role: string | undefined): boolean {
  return !!role && (BANNER_ELIGIBLE_ROLES as readonly string[]).includes(role);
}

/** Public-display predicate, mirrored from the RLS policy (defense in depth). */
export interface DisplayableInput {
  approval_status: string;
  status: string;
  is_paused: boolean;
  payment_status: string;
  start_date: string | null;
  end_date: string | null;
}
export function isPubliclyDisplayable(a: DisplayableInput, today = new Date()): boolean {
  if (a.approval_status !== "approved" || a.status !== "active" || a.is_paused) return false;
  if (!["not_required", "success"].includes(a.payment_status)) return false;
  if (!a.start_date || !a.end_date) return false;
  const d = today.toISOString().slice(0, 10);
  return a.start_date <= d && a.end_date >= d;
}

/** Allowed duration options (days). */
export const DURATION_OPTIONS = [3, 7, 15, 30] as const;
export type DurationDays = (typeof DURATION_OPTIONS)[number];

/** Per-device image guidance shown in the uploader. */
export interface DeviceRule {
  key: "desktop" | "mobile";
  label: string;
  recommended: string;
  ratio: string;
  minWidth: number;
  required: boolean;
}
// Housing.com "Top picks" style: ONE creative image per device. The left project
// card is generated by the platform — the advertiser uploads only this image.
export const DEVICE_RULES: DeviceRule[] = [
  { key: "desktop", label: "Desktop", recommended: "1600×900 px", ratio: "16:9 (landscape)", minWidth: 1200, required: bannerFeatures.desktopImageRequired },
  { key: "mobile", label: "Mobile", recommended: "1080×1080 px", ratio: "1:1 (square)", minWidth: 600, required: bannerFeatures.mobileImageRequired },
];

export const IMAGE_RULES = {
  accepted: ["image/jpeg", "image/jpg", "image/png", "image/webp"],
  acceptedLabel: "JPG, PNG or WEBP",
  maxBytes: 5 * 1024 * 1024,
  maxSizeLabel: "5 MB",
};

/** Status → human label + badge tone for dashboards. */
export const STATUS_META: Record<string, { label: string; tone: "neutral" | "info" | "success" | "warning" | "danger" }> = {
  draft: { label: "Draft", tone: "neutral" },
  pending: { label: "Pending review", tone: "info" },
  needs_changes: { label: "Needs changes", tone: "warning" },
  rejected: { label: "Rejected", tone: "danger" },
  active: { label: "Active", tone: "success" },
  paused: { label: "Paused", tone: "warning" },
  expired: { label: "Expired", tone: "neutral" },
  archived: { label: "Archived", tone: "neutral" },
};

/** Has this ad passed its end date? (used to render Expired in dashboards) */
export function isExpired(end_date: string | null, today = new Date()): boolean {
  if (!end_date) return false;
  return end_date < today.toISOString().slice(0, 10);
}

/** ₹ short format for the project card (single value). */
export function inr(v: number | null | undefined): string | null {
  if (!v) return null;
  if (v >= 10000000) return `₹${(v / 10000000).toFixed(2).replace(/\.00$/, "")} Cr`;
  if (v >= 100000) return `₹${(v / 100000).toFixed(2).replace(/\.00$/, "")} L`;
  return `₹${v.toLocaleString("en-IN")}`;
}

/** Price-range label from a min/max (units) or single price. */
export function priceRangeLabel(min: number | null, max: number | null, fallback: number | null): string | null {
  const lo = inr(min ?? fallback);
  const hi = inr(max ?? null);
  if (lo && hi && min !== max) return `${lo} - ${hi}`;
  return lo ?? null;
}

/** "2, 3 BHK" style label from distinct BHK values. */
export function bhkLabel(bhks: number[]): string | null {
  const uniq = [...new Set(bhks.filter((b) => b && b > 0))].sort((a, b) => a - b);
  if (uniq.length === 0) return null;
  return `${uniq.join(", ")} BHK`;
}

/**
 * Internal-only destination rule. External links are disabled, so a destination
 * must be a same-site path under an allowed prefix.
 */
const ALLOWED_DEST_PREFIXES = ["/search", "/property/", "/project/", "/pricing"];
export function validateDestination(raw: string): { ok: true; url: string } | { ok: false; message: string } {
  const url = (raw || "").trim();
  if (!url.startsWith("/") || url.startsWith("//")) {
    return { ok: false, message: "Destination must be an internal link starting with “/”." };
  }
  if (!ALLOWED_DEST_PREFIXES.some((p) => url === p || url.startsWith(p))) {
    return { ok: false, message: `Link must point to ${ALLOWED_DEST_PREFIXES.join(", ")}.` };
  }
  return { ok: true, url };
}
